### ISSUE TITLE
Refresh loop...

### ISSUE THREAD

**Issue by david-boles** [erikmaarten/go-game#2]
Whenever I open a grain it goes into a refresh loop. The left side introductory text shows up momentarily, with the left side still saying it's loading, and then the page refreshes... Let me know if there is any other information I can provide...

**Comment by david-boles** [comment]
Sorry, new to sandstorm... Seems to be a server websockets issue...

**Comment by erikmaarten** [comment]
So it wasn't a bug with the app itself? I'll close the issue then.

Thanks for taking the time to report though!
